name: Fortran CI – xyz_rmsd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Fortran compiler
      - name: Install gfortran
        run: sudo apt-get update && sudo apt-get install -y gfortran

      # Compile the code
      - name: Compile xyz_rmsd
        run: |
          gfortran -ffree-form -O2 -o xyz-rmsd.x xyz-rmsd.f

      # Run the program with a sample test
      # You need to provide one or more sample .xyz inputs in the repo for this to work
      - name: Run example usage
        run: |
          # Example: assuming you have a file test1.xyz in repo
          ./xyz-rmsd.x tests/test1.xyz tests/test2.xyz -a > tests/output.txt
      # Check that the program worked (modify as per your expected output)
      - name: Verify output
        run: |
          if grep -q "RMSD" tests/output.txt; then
            echo "Output looks good"
          else
            echo "Unexpected output, failing"
            cat output.txt
            exit 1
          fi
